### ISSUE TITLE
Links for download and CLIP model weights

### ISSUE THREAD

**Issue by xavibou** [om-ai-lab/RS5M#1]
Dear authors,
Thank you for your work! When will the dataset be available for download? Additionally, when will the weights of the CLIP model fine-tuned on the RS5M dataset will be released?
Thanks
Xavi

**Comment by zilunzhang** [comment]
> Dear authors, Thank you for your work! When will the dataset be available for download? Additionally, when will the weights of the CLIP model fine-tuned on the RS5M dataset will be released? Thanks Xavi

Hi,

The metainfo of this dataset has been released to huggingface, and you can download them through URLs. As for the image files, we are working on the copyright issues, hopefully we can release them in 2023. 

We are cleaning the codebase now, and the model weights will be released in a few months along with the training & inference code.

**Comment by zilunzhang** [comment]
> Dear authors, Thank you for your work! When will the dataset be available for download? Additionally, when will the weights of the CLIP model fine-tuned on the RS5M dataset will be released? Thanks Xavi

Hi, 

The weights have been released: https://huggingface.co/Zilun/GeoRSCLIP/tree/main

The updated instructions can be found in the readme.md of this repo.

Feel free to use them.

Best,

Zilun
