### ISSUE TITLE
【Image Size and GSD】

### ISSUE THREAD

**Issue by Luo-Z13** [om-ai-lab/RS5M#11]
Hello, I would like to inquire about the range of image dimensions and Ground Sampling Distance (GSD) in the RS5M dataset. It seems that this information is not specified in the paper. Thank you.

**Comment by zilunzhang** [comment]
> Hello, I would like to inquire about the range of image dimensions and Ground Sampling Distance (GSD) in the RS5M dataset. It seems that this information is not specified in the paper. Thank you.

Hi,

All images are RGB, and the statistics for size are shown in Figure 22 (Appendix).

Ground Sampling Distance is used as meta information to enrich the caption for images from FMoW.

Best,

Zilun

**Comment by Luo-Z13** [comment]
> > Hello, I would like to inquire about the range of image dimensions and Ground Sampling Distance (GSD) in the RS5M dataset. It seems that this information is not specified in the paper. Thank you.
> 
> Hi,
> 
> All images are RGB, and the statistics for size are shown in Figure 22 (Appendix).
> 
> Ground Sampling Distance is used as meta information to enrich the caption for images from FMoW.
> 
> Best,
> 
> Zilun

Thank you very much!
