### ISSUE TITLE
GeoRSCLIP ResNet-50 checkpoint

### ISSUE THREAD

**Issue by fazliimam** [om-ai-lab/RS5M#13]
Hi, could you share the pretrained weights for GeoRSCLIP in Resnet-50. It's not available in huggingface.

**Comment by zilunzhang** [comment]
> Hi, could you share the pretrained weights for GeoRSCLIP in Resnet-50. It's not available in huggingface.

Hi Fazli,

Thanks for your interest!

So far, we only trained the ViT-based GeoRSCLIP as we pointed out in our paper (section VI, subsection B; section VI, subsection C-6 and Figure 9 ).
