### ISSUE TITLE
msrgb and rgb

### ISSUE THREAD

**Issue by xulinui** [om-ai-lab/RS5M#14]
fmow/train/airport/airport_0/airport_0_0_msrgb.jpg,fmow,fmow_airport_0_0_msrgb.jpg,"above the Winter landscapes of Etimesgut, Turkey, the view is transfixed by airport at its center and center-left blocks. with sharpness ensured by a ground sample distance of 2.45 meters, it's a moment frozen from the utm zone 36S, timestamped 8 o'clock, February 7, 2002. this satellite image shows an airport close to a city"

fmow/train/airport/airport_0/airport_0_0_rgb.jpg,fmow,fmow_airport_0_0_rgb.jpg,"sailing over Etimesgut, Turkey in Winter, the lens emphasizes airport nestled at the center and center-left blocks. the details, highlighted by a ground sample distance of 2.45 meters, associate it with the utm zone 36S, time-stamped 8 o'clock, February 7, 2002. a satellite image of a large airport"

Hello,

I have a few questions regarding image datasets:

1.Are these two images the same?
2. Is "msrgb" an abbreviation for "multispectral RGB", referring to the selection of three bands (RGB channels) from a multispectral image, specifically from the fMoW-full dataset?
3. Does the "RGB" come from the fMoW-rgb dataset?
4. What is the difference between "msrgb" and "RGB"?
Thank you.

**Comment by zilunzhang** [comment]
Hi,

All of them are downloaded from: s3://spacenet-dataset/Hosted-Datasets/fmow/fmow-rgb

* (1) Yes, they should have the same source.

* (2), (3) and (4). Yes,  "msrgb" is an abbreviation for "multispectral RGB". I think "rgb" is the one only selecting RGB bands from the multispectral source, and "msrgb" is the synthetic one by merging all bands to RGB. Here is the citation from the FMoW paper:
     * "**_fMoW-rgb An alternative JPEG compressed version of the dataset, which is provided due to the large size of fMoW-full. For each pan-sharpened RGB image we simply perform a conversion to JPEG. For MSI images, we extract the RGB channels and save them as JPEGs_**"
