### ISSUE TITLE
请问RS-SD和SD的FID分数是如何计算的？

### ISSUE THREAD

**Issue by jaycecd** [om-ai-lab/RS5M#15]
感谢作者杰出的工作，构建了如此庞大的遥感数据集！
但关于RS-SD和SD的FID分数我有一点小小的疑问，希望能解答一下！
如下图所示，您使用了RS-SD和SD分别计算了FID分数：
![image](https://github.com/om-ai-lab/RS5M/assets/33342388/909b7531-c8ea-4629-8bb4-1b1525081063)
但我们知道，FID是需要样本的真实分布作为对照的：
![image](https://github.com/om-ai-lab/RS5M/assets/33342388/d4494997-a900-4e14-92c1-96d72f79c2e3)
因为不像图生图一样，有原图可以直接与生成的图像做对比，论文中的图24和25，均是文生图的示例，我的疑问是您的真值样本是如何构建的？即上面公式中的X是从哪里获得的？
期待您的回复，谢谢~~

**Comment by BinSpa** [comment]
您好，关于这个问题，首先在我们构建的测试数据集中，每张图像已经有了对应的文本标注，我们用这个文本标注分别用SD和RS-SD生成图像，并分别用这两组生成的图像和原本图像计算FID，这里的原始图像充当了原始数据分布的角色。关于图24和25，仅仅用来展示RS-SD和SD生成的遥感图像之间的差异，与FID的计算无关。具体关于FID的计算，我们follow了以下工作：https://github.com/mseitzer/pytorch-fid

**Comment by jaycecd** [comment]
感谢~~
