### ISSUE TITLE
The method for generating captions

### ISSUE THREAD

**Issue by chirmy** [om-ai-lab/RS5M#17]
Hello:
Thank you for sharing such great dataset and model. But I have a question, I noticed in your paper the method for generating captioins: captions can be employed by the tuned BLIP2 model (tuning details can be found in Appendix B10) [16] with the OPT 6.7B checkpoint in half-precision from Huggingface for caption generation.
Could you please send me your program for generating captions?
Thanks.

**Comment by zilunzhang** [comment]
Hi,

Please refer to the huggingface website: https://huggingface.co/docs/transformers/en/model_doc/blip-2
