### ISSUE TITLE
数据集形式

### ISSUE THREAD

**Issue by lebron-2016** [om-ai-lab/RS5M#2]
尊敬的作者您好：
      请问数据集的形式是怎样的呢？关于标签信息是不是只有图像标题（文字描述），是否还有类别、目标框或分割mask等标注信息？
      感谢！！

**Comment by zilunzhang** [comment]
您好：

数据集的形式是图文对，即一张图配一段对应的描述。

RS3子集中的BigEarthNet, FMoW, 以及MillionAID (train) 是有类别 (class label) 标注的。另外FMoW有物体的目标框标注（bbox）。至于其他的子集，它们并没有您说的标注。

**Comment by zilunzhang** [comment]
> 尊敬的作者您好：
> 请问数据集的形式是怎样的呢？关于标签信息是不是只有图像标题（文字描述），是否还有类别、目标框或分割mask等标注信息？
> 感谢！！

您好：

数据集的形式是图文对，即一张图配一段对应的描述。

RS3子集中的BigEarthNet, FMoW, 以及MillionAID (train) 是有类别 (class label) 标注的。另外FMoW有物体的目标框标注（bbox）。至于其他的子集，它们并没有您说的标注。

**Comment by lebron-2016** [comment]
了解了，谢谢您！！
