### ISSUE TITLE
fine-tuned checkpoint for RSICD and RSITMD

### ISSUE THREAD

**Issue by zzl0107** [om-ai-lab/RS5M#21]
Hello，could you please tell me where I can download the checkpoint fine-tuned on RSITMD and RSICD?Thank you very much

**Comment by zilunzhang** [comment]
> Hello，could you please tell me where I can download the checkpoint fine-tuned on RSITMD and RSICD?Thank you very much

https://huggingface.co/Zilun/GeoRSCLIP/blob/main/ckpt/RS5M_ViT-B-32_RET-2.pt

**Comment by AOPALUNPA** [comment]
Hello, can you provide the ckpt when tuning solely on the RSICD or RSITMD?
