### ISSUE TITLE
The checkpoint fine-tuned on RSITMD or RSICD

### ISSUE THREAD

**Issue by AOPALUNPA** [om-ai-lab/RS5M#23]
Hello, could you provide the checkpoint fine-tuned solely on RSITMD or RSICD? not RET-2. I cannot reproduce the result reported in the paper. The reproduced result is far worse than the reported one. THX a lot!

**Comment by AOPALUNPA** [comment]
I noticed there are several issues about this question, can you release the ckpt? Otherwise, I doubt the authenticity of the results.

**Comment by zilunzhang** [comment]
> I noticed there are several issues about this question, can you release the ckpt? Otherwise, I doubt the authenticity of the results.

Interesting. **Show your respect when asking something from others.** 

Can't you even wait 30 minutes to let us download the checkpoints from the server and convert the format? We reserve the right to not share ckpts with the one who doesn't understand **MANNERS**.

For anyone who asked the ckpt before, please email us. We will reply you with the checkpoint.

**Comment by AOPALUNPA** [comment]
I don't know about any perceived rudeness in our correspondence, as my intention has always been to engage in an academic discussion. I take these matters seriously and will reserve my rights to pursue this issue to its full extent.

**Comment by zilunzhang** [comment]
> I don't know about any perceived rudeness in our correspondence, as my intention has always been to engage in an academic discussion. I take these matters seriously and will reserve my rights to pursue this issue to its full extent.

Feel free to do so. We **DONT CARE**.

We do believe you have a bright future in scientific research.
