### ISSUE TITLE
Clip weights

### ISSUE THREAD

**Issue by Cemm23333** [om-ai-lab/RS5M#3]
Dear author, I would like to inquire about the release date for CLIP weights fine-tuned on the RS5M dataset. At present, it appears that only the BLIP-2 inference code is available.

**Comment by zilunzhang** [comment]
Hi,

The model weights will be released by the end of this month.

**Comment by Cemm23333** [comment]
Hello, do you have any plans to release the weights of CLIP recently ? The pre-trained CLIP weights pretrained on RS5M are crucial for many remote sensing tasks.Looking forward to your response.

**Comment by zilunzhang** [comment]
> Hello, do you have any plans to release the weights of CLIP recently ? The pre-trained CLIP weights pretrained on RS5M are crucial for many remote sensing tasks.Looking forward to your response.

Hi Cem,

We are re-training the fine-tuned CLIP model in different model sizes. We are sorry, the release date is a little bit delayed (a few days) because we transferred the old codebase to a new one (which resulted in a performance boost and faster training speed)

We will @you once the weights are uploaded.

Best, 

Zilun

**Comment by Cemm23333** [comment]
Thank you for your quick response. Looking forward to the retraining weights of  CLIP.

**Comment by zilunzhang** [comment]
> Thank you for your quick response. Looking forward to the retraining weights of CLIP.

Hi,

The weights have been released: https://huggingface.co/Zilun/GeoRSCLIP/tree/main

The updated instructions can be found in the readme.md of this repo.

Feel free to use them.

Best,

Zilun

**Comment by RAYRAYRAYRita** [comment]
> > Hello, do you have any plans to release the weights of CLIP recently ? The pre-trained CLIP weights pretrained on RS5M are crucial for many remote sensing tasks.Looking forward to your response.
> 
> Hi Cem,
> 
> We are re-training the fine-tuned CLIP model in different model sizes. We are sorry, the release date is a little bit delayed (a few days) because we transferred the old codebase to a new one (which resulted in a performance boost and faster training speed)
> 
> We will @you once the weights are uploaded.
> 
> Best,
> 
> Zilun

Thanks for great work and open-source!
I'm working on CLIP fine-tuning as well and have difficulties trying various peft/fully fine-tune codebase. So i'm curious about this new codebase or any recommendation about fine-tune? (I see openclip for fully tuning without any peft method?)
