### ISSUE TITLE
RS-SD(Stable diffusion model tuned with 1% RS5M)

### ISSUE THREAD

**Issue by walking-shadow** [om-ai-lab/RS5M#4]
Your work is fantastics! 
May the RS-SD model, fine-tuned with 1% of RS5M data, be released soon? What kind of fine-tuned method is used to created this model?

**Comment by zilunzhang** [comment]
Hi,

The dreambooth was applied to tune the RS-SD.

It will be released as well by the end of this month.

**Comment by zilunzhang** [comment]
Try this one: https://huggingface.co/Zilun/GeoRSSD

Sorry for the delay, we have been struggling with computational resources until this month.

Best,

Zilun
