### ISSUE TITLE
A  question about rs3 subset

### ISSUE THREAD

**Issue by fitzpchao** [om-ai-lab/RS5M#5]
Thank you for such a great work, RS5M. 
 I am following your work, and now I have encountered some problems. Now I would like to ask the following questions:
1. There are two caption tags on RS3, top - cap and ssl-cap. I don't know the meaning and difference between the two, especially ssl-cap. I also want to know which training model you finally used.
2. Where did you download the bigearthNet data set of RS? I saw that the officially downloaded file name is not the sequence ID, but the data sequence ID in your paper is 45786. I want to use this data now. What should I do? Where to download and how to process this data.
Very much looking forward to your reply！

**Comment by zilunzhang** [comment]
Hi,

1. Say we have 5 captions per image (top 5). top-cap is the top-1 cap of the image. ssl-cap is the one chosen from top-5 based on Rotation-invariant criteria (see the last few lines in paragraph 3 from section 3.2 for definition). We randomly chose the top-cap or ssl-cap when we were making the dataset (They could be the same one).

2. Sorry, it is our oversight. We extracted the RGB channels from the multi-spectral tif image and renamed it. We will upload the RGB images tmr somewhere for downloading. 

Best.

Zilun

**Comment by zilunzhang** [comment]
Baidu Disk

https://pan.baidu.com/s/1aCqRmnCeow18ry__R_oZow?pwd=6ya9 

Password: 6ya9

**Comment by fitzpchao** [comment]
Thanks for your reply and dataset!
