### ISSUE TITLE
训练数据问题

### ISSUE THREAD

**Issue by zhangch-ss** [om-ai-lab/RS5M#7]
您好，请问多个子集的影像尺寸不同，比如有的为500×500，有的是120×120，这块在训练前是怎么处理的呢？会统一训练影像的尺寸吗？

**Comment by zilunzhang** [comment]
Hi,

我们遵照openCLIP的预处理来处理的数据，最后所有图像输入都是resize成224x224

**Comment by zhangch-ss** [comment]
> Hi,
> 
> 我们遵照openCLIP的预处理来处理的数据，最后所有图像输入都是resize成224x224

thks
