### ISSUE TITLE
about RS-SD

### ISSUE THREAD

**Issue by jiangyuhangcn** [om-ai-lab/RS5M#8]
作者您好！在论文中看到您使用RS5M对stable diffusion进行了微调，我想咨询一下您具体是如何微调sd的？是否将包括vae在内的全部参数都打开微调了呢？如果方便的话您是否可以开源RS-SD的权重呢？十分感谢！

**Comment by zilunzhang** [comment]
你好，

RS-SD是用的dreambooth训练的，全参数微调。RS-SD是计划开源的，但一个问题是目前数据集迭代到了v5，但是RS-SD是用v3训的，所以我们还没想好是立刻开源v3版本的RS-SD还是等v5版本训练完再开源v5版本的RS-SD（可能下周训完）。这周末v5版本的CLIP权重会放出，arxiv上的paper也会更新。

感谢关注！

张孜纶

**Comment by jiangyuhangcn** [comment]
> 你好，
> 
> RS-SD是用的dreambooth训练的，全参数微调。RS-SD是计划开源的，但一个问题是目前数据集迭代到了v5，但是RS-SD是用v3训的，所以我们还没想好是立刻开源v3版本的RS-SD还是等v5版本训练完再开源v5版本的RS-SD（可能下周训完）。这周末v5版本的CLIP权重会放出，arxiv上的paper也会更新。
> 
> 感谢关注！
> 
> 张孜纶

感谢您的回复，期待RS-SD早日发布！
