### ISSUE TITLE
加载预训练权重时报错，维度不统一

### ISSUE THREAD

**Issue by ShuiJianan** [om-ai-lab/RS5M#9]
代码片段
ckpt_path = "E:\Modelpth\RS5M_ViT-B-32.pt"
model, _, _ = open_clip.create_model_and_transforms("ViT-B/32", pretrained="openai")
checkpoint = torch.load(ckpt_path, map_location="cpu")
msg = model.load_state_dict(checkpoint, strict=False)
model = model.to("cuda")
img_preprocess =   get_preprocess(
        image_resolution=224,
)
报错
RuntimeError: Error(s) in loading state_dict for CLIP:
	size mismatch for visual.positional_embedding: copying a param with shape torch.Size([50, 768]) from checkpoint, the shape in current model is torch.Size([65, 768]).

**Comment by zilunzhang** [comment]
你好，可否提供一下openclip的版本？

我们在Ubuntu和MacOS上复制你提供的代码测试刚从huggingface上下载下来的ckpt没有发现这个问题。

![WechatIMG160](https://github.com/om-ai-lab/RS5M/assets/22264060/f8f03d5a-758b-41bc-82ee-c577b27f1628)

此外，model.visual.positional_embedding的shape在我们这里显示的是(50, 768)，你遇到的问题可能是不同操作系统/openclip版本带来

**Comment by zilunzhang** [comment]
> 代码片段 ckpt_path = "E:\Modelpth\RS5M_ViT-B-32.pt" model, _, _ = open_clip.create_model_and_transforms("ViT-B/32", pretrained="openai") checkpoint = torch.load(ckpt_path, map_location="cpu") msg = model.load_state_dict(checkpoint, strict=False) model = model.to("cuda") img_preprocess = get_preprocess( image_resolution=224, ) 报错 RuntimeError: Error(s) in loading state_dict for CLIP: size mismatch for visual.positional_embedding: copying a param with shape torch.Size([50, 768]) from checkpoint, the shape in current model is torch.Size([65, 768]).

你好，可否提供一下openclip的版本？

我们在Ubuntu和MacOS上复制你提供的代码测试刚从huggingface上下载下来的ckpt没有发现这个问题。

![WechatIMG160](https://github.com/om-ai-lab/RS5M/assets/22264060/f8f03d5a-758b-41bc-82ee-c577b27f1628)

此外，model.visual.positional_embedding的shape在我们这里显示的是(50, 768)，你遇到的问题可能是不同操作系统/openclip版本带来

**Comment by ShuiJianan** [comment]
> > 代码片段 ckpt_path = "E:\Modelpth\RS5M_ViT-B-32.pt" model, _, _ = open_clip.create_model_and_transforms("ViT-B/32", pretrained="openai") checkpoint = torch.load(ckpt_path, map_location="cpu") msg = model.load_state_dict(checkpoint, strict=False) model = model.to("cuda") img_preprocess = get_preprocess( image_resolution=224, ) 报错 RuntimeError: Error(s) in loading state_dict for CLIP: size mismatch for visual.positional_embedding: copying a param with shape torch.Size([50, 768]) from checkpoint, the shape in current model is torch.Size([65, 768]).
> 
> 你好，可否提供一下openclip的版本？
> 
> 我们在Ubuntu和MacOS上复制你提供的代码测试刚从huggingface上下载下来的ckpt没有发现这个问题。
> 
> ![WechatIMG160](https://private-user-images.githubusercontent.com/22264060/289336774-f8f03d5a-758b-41bc-82ee-c577b27f1628.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxODQ1MjUsIm5iZiI6MTcwMjE4NDIyNSwicGF0aCI6Ii8yMjI2NDA2MC8yODkzMzY3NzQtZjhmMDNkNWEtNzU4Yi00MWJjLTgyZWUtYzU3N2IyN2YxNjI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA0NTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZTYxNDU4MzkxOTMwOGNlM2FlNjVhZTVjMjMwYWFlZGMxMTQ2OGNiZmU0ZWQ4MDQxY2NiMjY0YmQxYWI1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.deaX-jNXWo-NjQ1hZJpVvLzVVw31ikaQINwcv02m6rI)
> 
> 此外，model.visual.positional_embedding的shape在我们这里显示的是(50, 768)，你遇到的问题可能是不同操作系统/openclip版本带来

你好 很感谢你的回复。 我是在windows平台下进行测试的 我的openclip版本为 2.23.0
我重新安装了openclip 版本为2.20.0 现在问题已经解决了。
非常感谢你的解答
